<?php

// Register Custom Post Type
function cpt_wordcamps() {

	$labels = array(
		'name'                => _x( 'WordCamps', 'wp-rio-locale' ),
		'singular_name'       => _x( 'WordCamp', 'wp-rio-locale' ),
		'menu_name'           => __( 'WordCamps', 'wp-rio-locale' ),
		'name_admin_bar'      => __( 'WordCamps', 'wp-rio-locale' ),
		'parent_item_colon'   => __( 'WordCamp Pai', 'wp-rio-locale' ),
		'all_items'           => __( 'Todos os WordCamp', 'wp-rio-locale' ),
		'add_new_item'        => __( 'Adicionar novo WordCamp', 'wp-rio-locale' ),
		'add_new'             => __( 'Adicionar novo', 'wp-rio-locale' ),
		'new_item'            => __( 'Adicionar novo', 'wp-rio-locale' ),
		'edit_item'           => __( 'Editar WordCamp', 'wp-rio-locale' ),
		'update_item'         => __( 'Atualizar WordCamp', 'wp-rio-locale' ),
		'view_item'           => __( 'Ver WordCamp', 'wp-rio-locale' ),
		'search_items'        => __( 'Buscar WordCamp', 'wp-rio-locale' ),
		'not_found'           => __( 'Não Encontrado', 'wp-rio-locale' ),
		'not_found_in_trash'  => __( 'Não Encontrado na Lixeira', 'wp-rio-locale' ),
		);
$args = array(
	'label'               => __( 'Post Type', 'wp-rio-locale' ),
	'description'         => __( 'Postagens sobre os WordCamp', 'wp-rio-locale' ),
	'labels'              => $labels,
	'supports'            => array( 'title', 'editor', 'thumbnail' ),
	'taxonomies'          => array( ),
	'menu_icon'			  => 'dashicons-wordpress',
	'hierarchical'        => false,
	'public'              => true,
	'show_ui'             => true,
	'show_in_menu'        => true,
	'menu_position'       => 5,
	'show_in_admin_bar'   => true,
	'show_in_nav_menus'   => true,
	'can_export'          => true,
	'has_archive'         => true,
	'exclude_from_search' => false,
	'publicly_queryable'  => true,
	'capability_type'     => 'page',
	);
register_post_type( 'wordcamps', $args );

}
add_action( 'init', 'cpt_wordcamps', 0 );

function cpt_meetups() {

	$labels = array(
		'name'                => _x( 'Meetups', 'wp-rio-locale' ),
		'singular_name'       => _x( 'Meetup', 'wp-rio-locale' ),
		'menu_name'           => __( 'Meetups', 'wp-rio-locale' ),
		'name_admin_bar'      => __( 'Meetups', 'wp-rio-locale' ),
		'parent_item_colon'   => __( 'Meetup Pai', 'wp-rio-locale' ),
		'all_items'           => __( 'Todos os Meetups', 'wp-rio-locale' ),
		'add_new_item'        => __( 'Adicionar novo Meetup', 'wp-rio-locale' ),
		'add_new'             => __( 'Adicionar novo', 'wp-rio-locale' ),
		'new_item'            => __( 'Adicionar novo', 'wp-rio-locale' ),
		'edit_item'           => __( 'Editar Meetup', 'wp-rio-locale' ),
		'update_item'         => __( 'Atualizar Meetup', 'wp-rio-locale' ),
		'view_item'           => __( 'Ver Meetup', 'wp-rio-locale' ),
		'search_items'        => __( 'Buscar Meetup', 'wp-rio-locale' ),
		'not_found'           => __( 'Não Encontrado', 'wp-rio-locale' ),
		'not_found_in_trash'  => __( 'Não Encontrado na Lixeira', 'wp-rio-locale' ),
		);
$args = array(
	'label'               => __( 'Post Type', 'wp-rio-locale' ),
	'description'         => __( 'Postagens sobre os Meetups', 'wp-rio-locale' ),
	'labels'              => $labels,
	'supports'            => array( 'title', 'editor', 'thumbnail' ),
	'taxonomies'          => array( ),
	'menu_icon'			  => 'dashicons-wordpress-alt',
	'hierarchical'        => false,
	'public'              => true,
	'show_ui'             => true,
	'show_in_menu'        => true,
	'menu_position'       => 5,
	'show_in_admin_bar'   => true,
	'show_in_nav_menus'   => true,
	'can_export'          => true,
	'has_archive'         => true,
	'exclude_from_search' => false,
	'publicly_queryable'  => true,
	'capability_type'     => 'page',
	);
register_post_type( 'meetups', $args );

}
add_action( 'init', 'cpt_meetups', 0 );

function cpt_slides() {

	$labels = array(
		'name'                => _x( 'Slides', 'wp-rio-locale' ),
		'singular_name'       => _x( 'Slide', 'wp-rio-locale' ),
		'menu_name'           => __( 'Slides', 'wp-rio-locale' ),
		'name_admin_bar'      => __( 'Slides', 'wp-rio-locale' ),
		'parent_item_colon'   => __( 'Slide Pai', 'wp-rio-locale' ),
		'all_items'           => __( 'Todos os slides', 'wp-rio-locale' ),
		'add_new_item'        => __( 'Adicionar novo slide', 'wp-rio-locale' ),
		'add_new'             => __( 'Adicionar novo', 'wp-rio-locale' ),
		'new_item'            => __( 'Adicionar novo', 'wp-rio-locale' ),
		'edit_item'           => __( 'Editar slide', 'wp-rio-locale' ),
		'update_item'         => __( 'Atualizar slide', 'wp-rio-locale' ),
		'view_item'           => __( 'Ver slide', 'wp-rio-locale' ),
		'search_items'        => __( 'Buscar slide', 'wp-rio-locale' ),
		'not_found'           => __( 'Não Encontrado', 'wp-rio-locale' ),
		'not_found_in_trash'  => __( 'Não Encontrado na Lixeira', 'wp-rio-locale' ),
		);
	$args = array(
		'label'               => __( 'Post Type', 'wp-rio-locale' ),
		'labels'              => $labels,
		'supports'            => array( 'title', 'editor', 'thumbnail' ),
		'taxonomies'          => array( ),
		'menu_icon'			  => 'dashicons-media-interactive',
		'hierarchical'        => false,
		'public'              => false,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 5,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'can_export'          => true,
		'has_archive'         => false,
		'exclude_from_search' => true,
		'publicly_queryable'  => true,
		'capability_type'     => 'page',
		);
	register_post_type( 'slides', $args );

}
add_action( 'init', 'cpt_slides', 0 );

// Register Custom Taxonomy
function taxonomy_cidades_wordcamp() {

	$labels = array(
		'name'                       => _x( 'Cidades', 'Taxonomy General Name', 'wp-rio-locale' ),
		'singular_name'              => _x( 'Cidade', 'Taxonomy Singular Name', 'wp-rio-locale' ),
		'menu_name'                  => __( 'Cidades', 'wp-rio-locale' ),
		'all_items'                  => __( 'Todas as Cidades', 'wp-rio-locale' ),
		'parent_item'                => __( 'Cidade Pai', 'wp-rio-locale' ),
		'parent_item_colon'          => __( 'Cidade Pai:', 'wp-rio-locale' ),
		'new_item_name'              => __( 'Nova Cidade', 'wp-rio-locale' ),
		'add_new_item'               => __( 'Adicionar Cidade', 'wp-rio-locale' ),
		'edit_item'                  => __( 'Editar Cidade', 'wp-rio-locale' ),
		'update_item'                => __( 'Atualizar Cidade', 'wp-rio-locale' ),
		'view_item'                  => __( 'Ver Cidade', 'wp-rio-locale' ),
		'separate_items_with_commas' => __( 'Separar cidades por vírgulas', 'wp-rio-locale' ),
		'add_or_remove_items'        => __( 'Adicionar ou Remover Cidades', 'wp-rio-locale' ),
		'choose_from_most_used'      => __( 'Escolher as mais usadas', 'wp-rio-locale' ),
		'popular_items'              => __( 'Cidades Populares', 'wp-rio-locale' ),
		'search_items'               => __( 'Buscar Cidades', 'wp-rio-locale' ),
		'not_found'                  => __( 'Não Encontrado', 'wp-rio-locale' ),
		);
$args = array(
	'labels'                     => $labels,
	'hierarchical'               => true,
	'public'                     => true,
	'show_ui'                    => true,
	'show_admin_column'          => true,
	'show_in_nav_menus'          => true,
	'show_tagcloud'              => true,
	);
register_taxonomy( 'cidades', array( 'wordcamps' ), $args );

}
add_action( 'init', 'taxonomy_cidades_wordcamp', 0 );

// Chamadas do ACF
if( function_exists('acf_add_options_page') ) {
	acf_add_options_page();
}

if( function_exists('register_field_group') ){
	register_field_group(array (
		'key' => 'group_55d545658bc53',
		'title' => 'Meetups',
		'fields' => array (
			array (
				'key' => 'field_55d545663c3f3',
				'label' => 'Local',
				'name' => 'local-meetup',
				'prefix' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
				),
			array (
				'key' => 'field_55d545663c7db',
				'label' => 'Link do site oficial',
				'name' => 'link-meetup',
				'prefix' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
			),
),
'location' => array (
	array (
		array (
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'meetups',
			),
		),
	),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_55d546478739d',
	'title' => 'Quem Somos',
	'fields' => array (
		array (
			'key' => 'field_55d546fa6796e',
			'label' => 'Equipe',
			'name' => 'equipe',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Adicionar Nova Pessoa',
			'sub_fields' => array (
				array (
					'key' => 'field_55d5470a6796f',
					'label' => 'Nome',
					'name' => 'nome-pessoa',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
					),
				array (
					'key' => 'field_55d5473c67970',
					'label' => 'Foto Perfil',
					'name' => 'foto-perfil',
					'prefix' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					),
				array (
					'key' => 'field_55d5478b67971',
					'label' => 'Descrição',
					'name' => 'descricao',
					'prefix' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					),
				array (
					'key' => 'field_55d547f667972',
					'label' => 'Ícones Sociais',
					'name' => 'ícones-sociais',
					'prefix' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'min' => '',
					'max' => '',
					'layout' => 'row',
					'button_label' => 'Adicionar Linha',
					'sub_fields' => array (
						array (
			'key' => 'field_55d5481367973',
			'label' => 'Selecionar o ícone',
			'name' => 'classe-icone',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'null',
			'save_format' => 'element',
			'allow_null' => 0,
			'enqueue_fa' => 1,
			'fa_live_preview' => '',
			'choices' => array (
				'null' => '- Select -',
				'fa-500px' => ' fa-500px',
				'fa-adjust' => ' fa-adjust',
				'fa-adn' => ' fa-adn',
				'fa-align-center' => ' fa-align-center',
				'fa-align-justify' => ' fa-align-justify',
				'fa-align-left' => ' fa-align-left',
				'fa-align-right' => ' fa-align-right',
				'fa-amazon' => ' fa-amazon',
				'fa-ambulance' => ' fa-ambulance',
				'fa-anchor' => ' fa-anchor',
				'fa-android' => ' fa-android',
				'fa-angellist' => ' fa-angellist',
				'fa-angle-double-down' => ' fa-angle-double-down',
				'fa-angle-double-left' => ' fa-angle-double-left',
				'fa-angle-double-right' => ' fa-angle-double-right',
				'fa-angle-double-up' => ' fa-angle-double-up',
				'fa-angle-down' => ' fa-angle-down',
				'fa-angle-left' => ' fa-angle-left',
				'fa-angle-right' => ' fa-angle-right',
				'fa-angle-up' => ' fa-angle-up',
				'fa-apple' => ' fa-apple',
				'fa-archive' => ' fa-archive',
				'fa-area-chart' => ' fa-area-chart',
				'fa-arrow-circle-down' => ' fa-arrow-circle-down',
				'fa-arrow-circle-left' => ' fa-arrow-circle-left',
				'fa-arrow-circle-o-down' => ' fa-arrow-circle-o-down',
				'fa-arrow-circle-o-left' => ' fa-arrow-circle-o-left',
				'fa-arrow-circle-o-right' => ' fa-arrow-circle-o-right',
				'fa-arrow-circle-o-up' => ' fa-arrow-circle-o-up',
				'fa-arrow-circle-right' => ' fa-arrow-circle-right',
				'fa-arrow-circle-up' => ' fa-arrow-circle-up',
				'fa-arrow-down' => ' fa-arrow-down',
				'fa-arrow-left' => ' fa-arrow-left',
				'fa-arrow-right' => ' fa-arrow-right',
				'fa-arrow-up' => ' fa-arrow-up',
				'fa-arrows' => ' fa-arrows',
				'fa-arrows-alt' => ' fa-arrows-alt',
				'fa-arrows-h' => ' fa-arrows-h',
				'fa-arrows-v' => ' fa-arrows-v',
				'fa-asterisk' => ' fa-asterisk',
				'fa-at' => ' fa-at',
				'fa-backward' => ' fa-backward',
				'fa-balance-scale' => ' fa-balance-scale',
				'fa-ban' => ' fa-ban',
				'fa-bar-chart' => ' fa-bar-chart',
				'fa-barcode' => ' fa-barcode',
				'fa-bars' => ' fa-bars',
				'fa-battery-empty' => ' fa-battery-empty',
				'fa-battery-full' => ' fa-battery-full',
				'fa-battery-half' => ' fa-battery-half',
				'fa-battery-quarter' => ' fa-battery-quarter',
				'fa-battery-three-quarters' => ' fa-battery-three-quarters',
				'fa-bed' => ' fa-bed',
				'fa-beer' => ' fa-beer',
				'fa-behance' => ' fa-behance',
				'fa-behance-square' => ' fa-behance-square',
				'fa-bell' => ' fa-bell',
				'fa-bell-o' => ' fa-bell-o',
				'fa-bell-slash' => ' fa-bell-slash',
				'fa-bell-slash-o' => ' fa-bell-slash-o',
				'fa-bicycle' => ' fa-bicycle',
				'fa-binoculars' => ' fa-binoculars',
				'fa-birthday-cake' => ' fa-birthday-cake',
				'fa-bitbucket' => ' fa-bitbucket',
				'fa-bitbucket-square' => ' fa-bitbucket-square',
				'fa-black-tie' => ' fa-black-tie',
				'fa-bold' => ' fa-bold',
				'fa-bolt' => ' fa-bolt',
				'fa-bomb' => ' fa-bomb',
				'fa-book' => ' fa-book',
				'fa-bookmark' => ' fa-bookmark',
				'fa-bookmark-o' => ' fa-bookmark-o',
				'fa-briefcase' => ' fa-briefcase',
				'fa-btc' => ' fa-btc',
				'fa-bug' => ' fa-bug',
				'fa-building' => ' fa-building',
				'fa-building-o' => ' fa-building-o',
				'fa-bullhorn' => ' fa-bullhorn',
				'fa-bullseye' => ' fa-bullseye',
				'fa-bus' => ' fa-bus',
				'fa-buysellads' => ' fa-buysellads',
				'fa-calculator' => ' fa-calculator',
				'fa-calendar' => ' fa-calendar',
				'fa-calendar-check-o' => ' fa-calendar-check-o',
				'fa-calendar-minus-o' => ' fa-calendar-minus-o',
				'fa-calendar-o' => ' fa-calendar-o',
				'fa-calendar-plus-o' => ' fa-calendar-plus-o',
				'fa-calendar-times-o' => ' fa-calendar-times-o',
				'fa-camera' => ' fa-camera',
				'fa-camera-retro' => ' fa-camera-retro',
				'fa-car' => ' fa-car',
				'fa-caret-down' => ' fa-caret-down',
				'fa-caret-left' => ' fa-caret-left',
				'fa-caret-right' => ' fa-caret-right',
				'fa-caret-square-o-down' => ' fa-caret-square-o-down',
				'fa-caret-square-o-left' => ' fa-caret-square-o-left',
				'fa-caret-square-o-right' => ' fa-caret-square-o-right',
				'fa-caret-square-o-up' => ' fa-caret-square-o-up',
				'fa-caret-up' => ' fa-caret-up',
				'fa-cart-arrow-down' => ' fa-cart-arrow-down',
				'fa-cart-plus' => ' fa-cart-plus',
				'fa-cc' => ' fa-cc',
				'fa-cc-amex' => ' fa-cc-amex',
				'fa-cc-diners-club' => ' fa-cc-diners-club',
				'fa-cc-discover' => ' fa-cc-discover',
				'fa-cc-jcb' => ' fa-cc-jcb',
				'fa-cc-mastercard' => ' fa-cc-mastercard',
				'fa-cc-paypal' => ' fa-cc-paypal',
				'fa-cc-stripe' => ' fa-cc-stripe',
				'fa-cc-visa' => ' fa-cc-visa',
				'fa-certificate' => ' fa-certificate',
				'fa-chain-broken' => ' fa-chain-broken',
				'fa-check' => ' fa-check',
				'fa-check-circle' => ' fa-check-circle',
				'fa-check-circle-o' => ' fa-check-circle-o',
				'fa-check-square' => ' fa-check-square',
				'fa-check-square-o' => ' fa-check-square-o',
				'fa-chevron-circle-down' => ' fa-chevron-circle-down',
				'fa-chevron-circle-left' => ' fa-chevron-circle-left',
				'fa-chevron-circle-right' => ' fa-chevron-circle-right',
				'fa-chevron-circle-up' => ' fa-chevron-circle-up',
				'fa-chevron-down' => ' fa-chevron-down',
				'fa-chevron-left' => ' fa-chevron-left',
				'fa-chevron-right' => ' fa-chevron-right',
				'fa-chevron-up' => ' fa-chevron-up',
				'fa-child' => ' fa-child',
				'fa-chrome' => ' fa-chrome',
				'fa-circle' => ' fa-circle',
				'fa-circle-o' => ' fa-circle-o',
				'fa-circle-o-notch' => ' fa-circle-o-notch',
				'fa-circle-thin' => ' fa-circle-thin',
				'fa-clipboard' => ' fa-clipboard',
				'fa-clock-o' => ' fa-clock-o',
				'fa-clone' => ' fa-clone',
				'fa-cloud' => ' fa-cloud',
				'fa-cloud-download' => ' fa-cloud-download',
				'fa-cloud-upload' => ' fa-cloud-upload',
				'fa-code' => ' fa-code',
				'fa-code-fork' => ' fa-code-fork',
				'fa-codepen' => ' fa-codepen',
				'fa-coffee' => ' fa-coffee',
				'fa-cog' => ' fa-cog',
				'fa-cogs' => ' fa-cogs',
				'fa-columns' => ' fa-columns',
				'fa-comment' => ' fa-comment',
				'fa-comment-o' => ' fa-comment-o',
				'fa-commenting' => ' fa-commenting',
				'fa-commenting-o' => ' fa-commenting-o',
				'fa-comments' => ' fa-comments',
				'fa-comments-o' => ' fa-comments-o',
				'fa-compass' => ' fa-compass',
				'fa-compress' => ' fa-compress',
				'fa-connectdevelop' => ' fa-connectdevelop',
				'fa-contao' => ' fa-contao',
				'fa-copyright' => ' fa-copyright',
				'fa-creative-commons' => ' fa-creative-commons',
				'fa-credit-card' => ' fa-credit-card',
				'fa-crop' => ' fa-crop',
				'fa-crosshairs' => ' fa-crosshairs',
				'fa-css3' => ' fa-css3',
				'fa-cube' => ' fa-cube',
				'fa-cubes' => ' fa-cubes',
				'fa-cutlery' => ' fa-cutlery',
				'fa-dashcube' => ' fa-dashcube',
				'fa-database' => ' fa-database',
				'fa-delicious' => ' fa-delicious',
				'fa-desktop' => ' fa-desktop',
				'fa-deviantart' => ' fa-deviantart',
				'fa-diamond' => ' fa-diamond',
				'fa-digg' => ' fa-digg',
				'fa-dot-circle-o' => ' fa-dot-circle-o',
				'fa-download' => ' fa-download',
				'fa-dribbble' => ' fa-dribbble',
				'fa-dropbox' => ' fa-dropbox',
				'fa-drupal' => ' fa-drupal',
				'fa-eject' => ' fa-eject',
				'fa-ellipsis-h' => ' fa-ellipsis-h',
				'fa-ellipsis-v' => ' fa-ellipsis-v',
				'fa-empire' => ' fa-empire',
				'fa-envelope' => ' fa-envelope',
				'fa-envelope-o' => ' fa-envelope-o',
				'fa-envelope-square' => ' fa-envelope-square',
				'fa-eraser' => ' fa-eraser',
				'fa-eur' => ' fa-eur',
				'fa-exchange' => ' fa-exchange',
				'fa-exclamation' => ' fa-exclamation',
				'fa-exclamation-circle' => ' fa-exclamation-circle',
				'fa-exclamation-triangle' => ' fa-exclamation-triangle',
				'fa-expand' => ' fa-expand',
				'fa-expeditedssl' => ' fa-expeditedssl',
				'fa-external-link' => ' fa-external-link',
				'fa-external-link-square' => ' fa-external-link-square',
				'fa-eye' => ' fa-eye',
				'fa-eye-slash' => ' fa-eye-slash',
				'fa-eyedropper' => ' fa-eyedropper',
				'fa-facebook' => ' fa-facebook',
				'fa-facebook-official' => ' fa-facebook-official',
				'fa-facebook-square' => ' fa-facebook-square',
				'fa-fast-backward' => ' fa-fast-backward',
				'fa-fast-forward' => ' fa-fast-forward',
				'fa-fax' => ' fa-fax',
				'fa-female' => ' fa-female',
				'fa-fighter-jet' => ' fa-fighter-jet',
				'fa-file' => ' fa-file',
				'fa-file-archive-o' => ' fa-file-archive-o',
				'fa-file-audio-o' => ' fa-file-audio-o',
				'fa-file-code-o' => ' fa-file-code-o',
				'fa-file-excel-o' => ' fa-file-excel-o',
				'fa-file-image-o' => ' fa-file-image-o',
				'fa-file-o' => ' fa-file-o',
				'fa-file-pdf-o' => ' fa-file-pdf-o',
				'fa-file-powerpoint-o' => ' fa-file-powerpoint-o',
				'fa-file-text' => ' fa-file-text',
				'fa-file-text-o' => ' fa-file-text-o',
				'fa-file-video-o' => ' fa-file-video-o',
				'fa-file-word-o' => ' fa-file-word-o',
				'fa-files-o' => ' fa-files-o',
				'fa-film' => ' fa-film',
				'fa-filter' => ' fa-filter',
				'fa-fire' => ' fa-fire',
				'fa-fire-extinguisher' => ' fa-fire-extinguisher',
				'fa-firefox' => ' fa-firefox',
				'fa-flag' => ' fa-flag',
				'fa-flag-checkered' => ' fa-flag-checkered',
				'fa-flag-o' => ' fa-flag-o',
				'fa-flask' => ' fa-flask',
				'fa-flickr' => ' fa-flickr',
				'fa-floppy-o' => ' fa-floppy-o',
				'fa-folder' => ' fa-folder',
				'fa-folder-o' => ' fa-folder-o',
				'fa-folder-open' => ' fa-folder-open',
				'fa-folder-open-o' => ' fa-folder-open-o',
				'fa-font' => ' fa-font',
				'fa-fonticons' => ' fa-fonticons',
				'fa-forumbee' => ' fa-forumbee',
				'fa-forward' => ' fa-forward',
				'fa-foursquare' => ' fa-foursquare',
				'fa-frown-o' => ' fa-frown-o',
				'fa-futbol-o' => ' fa-futbol-o',
				'fa-gamepad' => ' fa-gamepad',
				'fa-gavel' => ' fa-gavel',
				'fa-gbp' => ' fa-gbp',
				'fa-genderless' => ' fa-genderless',
				'fa-get-pocket' => ' fa-get-pocket',
				'fa-gg' => ' fa-gg',
				'fa-gg-circle' => ' fa-gg-circle',
				'fa-gift' => ' fa-gift',
				'fa-git' => ' fa-git',
				'fa-git-square' => ' fa-git-square',
				'fa-github' => ' fa-github',
				'fa-github-alt' => ' fa-github-alt',
				'fa-github-square' => ' fa-github-square',
				'fa-glass' => ' fa-glass',
				'fa-globe' => ' fa-globe',
				'fa-google' => ' fa-google',
				'fa-google-plus' => ' fa-google-plus',
				'fa-google-plus-square' => ' fa-google-plus-square',
				'fa-google-wallet' => ' fa-google-wallet',
				'fa-graduation-cap' => ' fa-graduation-cap',
				'fa-gratipay' => ' fa-gratipay',
				'fa-h-square' => ' fa-h-square',
				'fa-hacker-news' => ' fa-hacker-news',
				'fa-hand-lizard-o' => ' fa-hand-lizard-o',
				'fa-hand-o-down' => ' fa-hand-o-down',
				'fa-hand-o-left' => ' fa-hand-o-left',
				'fa-hand-o-right' => ' fa-hand-o-right',
				'fa-hand-o-up' => ' fa-hand-o-up',
				'fa-hand-paper-o' => ' fa-hand-paper-o',
				'fa-hand-peace-o' => ' fa-hand-peace-o',
				'fa-hand-pointer-o' => ' fa-hand-pointer-o',
				'fa-hand-rock-o' => ' fa-hand-rock-o',
				'fa-hand-scissors-o' => ' fa-hand-scissors-o',
				'fa-hand-spock-o' => ' fa-hand-spock-o',
				'fa-hdd-o' => ' fa-hdd-o',
				'fa-header' => ' fa-header',
				'fa-headphones' => ' fa-headphones',
				'fa-heart' => ' fa-heart',
				'fa-heart-o' => ' fa-heart-o',
				'fa-heartbeat' => ' fa-heartbeat',
				'fa-history' => ' fa-history',
				'fa-home' => ' fa-home',
				'fa-hospital-o' => ' fa-hospital-o',
				'fa-hourglass' => ' fa-hourglass',
				'fa-hourglass-end' => ' fa-hourglass-end',
				'fa-hourglass-half' => ' fa-hourglass-half',
				'fa-hourglass-o' => ' fa-hourglass-o',
				'fa-hourglass-start' => ' fa-hourglass-start',
				'fa-houzz' => ' fa-houzz',
				'fa-html5' => ' fa-html5',
				'fa-i-cursor' => ' fa-i-cursor',
				'fa-ils' => ' fa-ils',
				'fa-inbox' => ' fa-inbox',
				'fa-indent' => ' fa-indent',
				'fa-industry' => ' fa-industry',
				'fa-info' => ' fa-info',
				'fa-info-circle' => ' fa-info-circle',
				'fa-inr' => ' fa-inr',
				'fa-instagram' => ' fa-instagram',
				'fa-internet-explorer' => ' fa-internet-explorer',
				'fa-ioxhost' => ' fa-ioxhost',
				'fa-italic' => ' fa-italic',
				'fa-joomla' => ' fa-joomla',
				'fa-jpy' => ' fa-jpy',
				'fa-jsfiddle' => ' fa-jsfiddle',
				'fa-key' => ' fa-key',
				'fa-keyboard-o' => ' fa-keyboard-o',
				'fa-krw' => ' fa-krw',
				'fa-language' => ' fa-language',
				'fa-laptop' => ' fa-laptop',
				'fa-lastfm' => ' fa-lastfm',
				'fa-lastfm-square' => ' fa-lastfm-square',
				'fa-leaf' => ' fa-leaf',
				'fa-leanpub' => ' fa-leanpub',
				'fa-lemon-o' => ' fa-lemon-o',
				'fa-level-down' => ' fa-level-down',
				'fa-level-up' => ' fa-level-up',
				'fa-life-ring' => ' fa-life-ring',
				'fa-lightbulb-o' => ' fa-lightbulb-o',
				'fa-line-chart' => ' fa-line-chart',
				'fa-link' => ' fa-link',
				'fa-linkedin' => ' fa-linkedin',
				'fa-linkedin-square' => ' fa-linkedin-square',
				'fa-linux' => ' fa-linux',
				'fa-list' => ' fa-list',
				'fa-list-alt' => ' fa-list-alt',
				'fa-list-ol' => ' fa-list-ol',
				'fa-list-ul' => ' fa-list-ul',
				'fa-location-arrow' => ' fa-location-arrow',
				'fa-lock' => ' fa-lock',
				'fa-long-arrow-down' => ' fa-long-arrow-down',
				'fa-long-arrow-left' => ' fa-long-arrow-left',
				'fa-long-arrow-right' => ' fa-long-arrow-right',
				'fa-long-arrow-up' => ' fa-long-arrow-up',
				'fa-magic' => ' fa-magic',
				'fa-magnet' => ' fa-magnet',
				'fa-male' => ' fa-male',
				'fa-map' => ' fa-map',
				'fa-map-marker' => ' fa-map-marker',
				'fa-map-o' => ' fa-map-o',
				'fa-map-pin' => ' fa-map-pin',
				'fa-map-signs' => ' fa-map-signs',
				'fa-mars' => ' fa-mars',
				'fa-mars-double' => ' fa-mars-double',
				'fa-mars-stroke' => ' fa-mars-stroke',
				'fa-mars-stroke-h' => ' fa-mars-stroke-h',
				'fa-mars-stroke-v' => ' fa-mars-stroke-v',
				'fa-maxcdn' => ' fa-maxcdn',
				'fa-meanpath' => ' fa-meanpath',
				'fa-medium' => ' fa-medium',
				'fa-medkit' => ' fa-medkit',
				'fa-meh-o' => ' fa-meh-o',
				'fa-mercury' => ' fa-mercury',
				'fa-microphone' => ' fa-microphone',
				'fa-microphone-slash' => ' fa-microphone-slash',
				'fa-minus' => ' fa-minus',
				'fa-minus-circle' => ' fa-minus-circle',
				'fa-minus-square' => ' fa-minus-square',
				'fa-minus-square-o' => ' fa-minus-square-o',
				'fa-mobile' => ' fa-mobile',
				'fa-money' => ' fa-money',
				'fa-moon-o' => ' fa-moon-o',
				'fa-motorcycle' => ' fa-motorcycle',
				'fa-mouse-pointer' => ' fa-mouse-pointer',
				'fa-music' => ' fa-music',
				'fa-neuter' => ' fa-neuter',
				'fa-newspaper-o' => ' fa-newspaper-o',
				'fa-object-group' => ' fa-object-group',
				'fa-object-ungroup' => ' fa-object-ungroup',
				'fa-odnoklassniki' => ' fa-odnoklassniki',
				'fa-odnoklassniki-square' => ' fa-odnoklassniki-square',
				'fa-opencart' => ' fa-opencart',
				'fa-openid' => ' fa-openid',
				'fa-opera' => ' fa-opera',
				'fa-optin-monster' => ' fa-optin-monster',
				'fa-outdent' => ' fa-outdent',
				'fa-pagelines' => ' fa-pagelines',
				'fa-paint-brush' => ' fa-paint-brush',
				'fa-paper-plane' => ' fa-paper-plane',
				'fa-paper-plane-o' => ' fa-paper-plane-o',
				'fa-paperclip' => ' fa-paperclip',
				'fa-paragraph' => ' fa-paragraph',
				'fa-pause' => ' fa-pause',
				'fa-paw' => ' fa-paw',
				'fa-paypal' => ' fa-paypal',
				'fa-pencil' => ' fa-pencil',
				'fa-pencil-square' => ' fa-pencil-square',
				'fa-pencil-square-o' => ' fa-pencil-square-o',
				'fa-phone' => ' fa-phone',
				'fa-phone-square' => ' fa-phone-square',
				'fa-picture-o' => ' fa-picture-o',
				'fa-pie-chart' => ' fa-pie-chart',
				'fa-pied-piper' => ' fa-pied-piper',
				'fa-pied-piper-alt' => ' fa-pied-piper-alt',
				'fa-pinterest' => ' fa-pinterest',
				'fa-pinterest-p' => ' fa-pinterest-p',
				'fa-pinterest-square' => ' fa-pinterest-square',
				'fa-plane' => ' fa-plane',
				'fa-play' => ' fa-play',
				'fa-play-circle' => ' fa-play-circle',
				'fa-play-circle-o' => ' fa-play-circle-o',
				'fa-plug' => ' fa-plug',
				'fa-plus' => ' fa-plus',
				'fa-plus-circle' => ' fa-plus-circle',
				'fa-plus-square' => ' fa-plus-square',
				'fa-plus-square-o' => ' fa-plus-square-o',
				'fa-power-off' => ' fa-power-off',
				'fa-print' => ' fa-print',
				'fa-puzzle-piece' => ' fa-puzzle-piece',
				'fa-qq' => ' fa-qq',
				'fa-qrcode' => ' fa-qrcode',
				'fa-question' => ' fa-question',
				'fa-question-circle' => ' fa-question-circle',
				'fa-quote-left' => ' fa-quote-left',
				'fa-quote-right' => ' fa-quote-right',
				'fa-random' => ' fa-random',
				'fa-rebel' => ' fa-rebel',
				'fa-recycle' => ' fa-recycle',
				'fa-reddit' => ' fa-reddit',
				'fa-reddit-square' => ' fa-reddit-square',
				'fa-refresh' => ' fa-refresh',
				'fa-registered' => ' fa-registered',
				'fa-renren' => ' fa-renren',
				'fa-repeat' => ' fa-repeat',
				'fa-reply' => ' fa-reply',
				'fa-reply-all' => ' fa-reply-all',
				'fa-retweet' => ' fa-retweet',
				'fa-road' => ' fa-road',
				'fa-rocket' => ' fa-rocket',
				'fa-rss' => ' fa-rss',
				'fa-rss-square' => ' fa-rss-square',
				'fa-rub' => ' fa-rub',
				'fa-safari' => ' fa-safari',
				'fa-scissors' => ' fa-scissors',
				'fa-search' => ' fa-search',
				'fa-search-minus' => ' fa-search-minus',
				'fa-search-plus' => ' fa-search-plus',
				'fa-sellsy' => ' fa-sellsy',
				'fa-server' => ' fa-server',
				'fa-share' => ' fa-share',
				'fa-share-alt' => ' fa-share-alt',
				'fa-share-alt-square' => ' fa-share-alt-square',
				'fa-share-square' => ' fa-share-square',
				'fa-share-square-o' => ' fa-share-square-o',
				'fa-shield' => ' fa-shield',
				'fa-ship' => ' fa-ship',
				'fa-shirtsinbulk' => ' fa-shirtsinbulk',
				'fa-shopping-cart' => ' fa-shopping-cart',
				'fa-sign-in' => ' fa-sign-in',
				'fa-sign-out' => ' fa-sign-out',
				'fa-signal' => ' fa-signal',
				'fa-simplybuilt' => ' fa-simplybuilt',
				'fa-sitemap' => ' fa-sitemap',
				'fa-skyatlas' => ' fa-skyatlas',
				'fa-skype' => ' fa-skype',
				'fa-slack' => ' fa-slack',
				'fa-sliders' => ' fa-sliders',
				'fa-slideshare' => ' fa-slideshare',
				'fa-smile-o' => ' fa-smile-o',
				'fa-sort' => ' fa-sort',
				'fa-sort-alpha-asc' => ' fa-sort-alpha-asc',
				'fa-sort-alpha-desc' => ' fa-sort-alpha-desc',
				'fa-sort-amount-asc' => ' fa-sort-amount-asc',
				'fa-sort-amount-desc' => ' fa-sort-amount-desc',
				'fa-sort-asc' => ' fa-sort-asc',
				'fa-sort-desc' => ' fa-sort-desc',
				'fa-sort-numeric-asc' => ' fa-sort-numeric-asc',
				'fa-sort-numeric-desc' => ' fa-sort-numeric-desc',
				'fa-soundcloud' => ' fa-soundcloud',
				'fa-space-shuttle' => ' fa-space-shuttle',
				'fa-spinner' => ' fa-spinner',
				'fa-spoon' => ' fa-spoon',
				'fa-spotify' => ' fa-spotify',
				'fa-square' => ' fa-square',
				'fa-square-o' => ' fa-square-o',
				'fa-stack-exchange' => ' fa-stack-exchange',
				'fa-stack-overflow' => ' fa-stack-overflow',
				'fa-star' => ' fa-star',
				'fa-star-half' => ' fa-star-half',
				'fa-star-half-o' => ' fa-star-half-o',
				'fa-star-o' => ' fa-star-o',
				'fa-steam' => ' fa-steam',
				'fa-steam-square' => ' fa-steam-square',
				'fa-step-backward' => ' fa-step-backward',
				'fa-step-forward' => ' fa-step-forward',
				'fa-stethoscope' => ' fa-stethoscope',
				'fa-sticky-note' => ' fa-sticky-note',
				'fa-sticky-note-o' => ' fa-sticky-note-o',
				'fa-stop' => ' fa-stop',
				'fa-street-view' => ' fa-street-view',
				'fa-strikethrough' => ' fa-strikethrough',
				'fa-stumbleupon' => ' fa-stumbleupon',
				'fa-stumbleupon-circle' => ' fa-stumbleupon-circle',
				'fa-subscript' => ' fa-subscript',
				'fa-subway' => ' fa-subway',
				'fa-suitcase' => ' fa-suitcase',
				'fa-sun-o' => ' fa-sun-o',
				'fa-superscript' => ' fa-superscript',
				'fa-table' => ' fa-table',
				'fa-tablet' => ' fa-tablet',
				'fa-tachometer' => ' fa-tachometer',
				'fa-tag' => ' fa-tag',
				'fa-tags' => ' fa-tags',
				'fa-tasks' => ' fa-tasks',
				'fa-taxi' => ' fa-taxi',
				'fa-television' => ' fa-television',
				'fa-tencent-weibo' => ' fa-tencent-weibo',
				'fa-terminal' => ' fa-terminal',
				'fa-text-height' => ' fa-text-height',
				'fa-text-width' => ' fa-text-width',
				'fa-th' => ' fa-th',
				'fa-th-large' => ' fa-th-large',
				'fa-th-list' => ' fa-th-list',
				'fa-thumb-tack' => ' fa-thumb-tack',
				'fa-thumbs-down' => ' fa-thumbs-down',
				'fa-thumbs-o-down' => ' fa-thumbs-o-down',
				'fa-thumbs-o-up' => ' fa-thumbs-o-up',
				'fa-thumbs-up' => ' fa-thumbs-up',
				'fa-ticket' => ' fa-ticket',
				'fa-times' => ' fa-times',
				'fa-times-circle' => ' fa-times-circle',
				'fa-times-circle-o' => ' fa-times-circle-o',
				'fa-tint' => ' fa-tint',
				'fa-toggle-off' => ' fa-toggle-off',
				'fa-toggle-on' => ' fa-toggle-on',
				'fa-trademark' => ' fa-trademark',
				'fa-train' => ' fa-train',
				'fa-transgender' => ' fa-transgender',
				'fa-transgender-alt' => ' fa-transgender-alt',
				'fa-trash' => ' fa-trash',
				'fa-trash-o' => ' fa-trash-o',
				'fa-tree' => ' fa-tree',
				'fa-trello' => ' fa-trello',
				'fa-tripadvisor' => ' fa-tripadvisor',
				'fa-trophy' => ' fa-trophy',
				'fa-truck' => ' fa-truck',
				'fa-try' => ' fa-try',
				'fa-tty' => ' fa-tty',
				'fa-tumblr' => ' fa-tumblr',
				'fa-tumblr-square' => ' fa-tumblr-square',
				'fa-twitch' => ' fa-twitch',
				'fa-twitter' => ' fa-twitter',
				'fa-twitter-square' => ' fa-twitter-square',
				'fa-umbrella' => ' fa-umbrella',
				'fa-underline' => ' fa-underline',
				'fa-undo' => ' fa-undo',
				'fa-university' => ' fa-university',
				'fa-unlock' => ' fa-unlock',
				'fa-unlock-alt' => ' fa-unlock-alt',
				'fa-upload' => ' fa-upload',
				'fa-usd' => ' fa-usd',
				'fa-user' => ' fa-user',
				'fa-user-md' => ' fa-user-md',
				'fa-user-plus' => ' fa-user-plus',
				'fa-user-secret' => ' fa-user-secret',
				'fa-user-times' => ' fa-user-times',
				'fa-users' => ' fa-users',
				'fa-venus' => ' fa-venus',
				'fa-venus-double' => ' fa-venus-double',
				'fa-venus-mars' => ' fa-venus-mars',
				'fa-viacoin' => ' fa-viacoin',
				'fa-video-camera' => ' fa-video-camera',
				'fa-vimeo' => ' fa-vimeo',
				'fa-vimeo-square' => ' fa-vimeo-square',
				'fa-vine' => ' fa-vine',
				'fa-vk' => ' fa-vk',
				'fa-volume-down' => ' fa-volume-down',
				'fa-volume-off' => ' fa-volume-off',
				'fa-volume-up' => ' fa-volume-up',
				'fa-weibo' => ' fa-weibo',
				'fa-weixin' => ' fa-weixin',
				'fa-whatsapp' => ' fa-whatsapp',
				'fa-wheelchair' => ' fa-wheelchair',
				'fa-wifi' => ' fa-wifi',
				'fa-wikipedia-w' => ' fa-wikipedia-w',
				'fa-windows' => ' fa-windows',
				'fa-wordpress' => ' fa-wordpress',
				'fa-wrench' => ' fa-wrench',
				'fa-xing' => ' fa-xing',
				'fa-xing-square' => ' fa-xing-square',
				'fa-y-combinator' => ' fa-y-combinator',
				'fa-yahoo' => ' fa-yahoo',
				'fa-yelp' => ' fa-yelp',
				'fa-youtube' => ' fa-youtube',
				'fa-youtube-play' => ' fa-youtube-play',
				'fa-youtube-square' => ' fa-youtube-square',
			),
		),
						array (
							'key' => 'field_55d5484367974',
							'label' => 'Link da Rede',
							'name' => 'link-rede',
							'prefix' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							),
						),
					),
),
),
),
'location' => array (
	array (
		array (
			'param' => 'page_template',
			'operator' => '==',
			'value' => 'template-quem-somos.php',
			),
		),
	),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_55d53f4acc7a6',
	'title' => 'Rodapé',
	'fields' => array (
		array (
			'key' => 'field_55d541b66741a',
			'label' => 'Exibir ícones sociais',
			'name' => 'show-icons',
			'prefix' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'message' => '',
			'default_value' => 0,
			),
		array (
			'key' => 'field_55d53f5172fd4',
			'label' => 'Ícones Sociais',
			'name' => 'social-icons',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55d541b66741a',
						'operator' => '==',
						'value' => '1',
						),
					),
				),
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Adicionar Novo Ícone',
			'sub_fields' => array (
				array (
			'key' => 'field_55d53fdb9c517',
			'label' => 'Classe do ícone',
			'name' => 'icon-class-footer',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'null',
			'save_format' => 'element',
			'allow_null' => 0,
			'enqueue_fa' => 1,
			'fa_live_preview' => '',
			'choices' => array (
				'null' => '- Select -',
				'fa-500px' => ' fa-500px',
				'fa-adjust' => ' fa-adjust',
				'fa-adn' => ' fa-adn',
				'fa-align-center' => ' fa-align-center',
				'fa-align-justify' => ' fa-align-justify',
				'fa-align-left' => ' fa-align-left',
				'fa-align-right' => ' fa-align-right',
				'fa-amazon' => ' fa-amazon',
				'fa-ambulance' => ' fa-ambulance',
				'fa-anchor' => ' fa-anchor',
				'fa-android' => ' fa-android',
				'fa-angellist' => ' fa-angellist',
				'fa-angle-double-down' => ' fa-angle-double-down',
				'fa-angle-double-left' => ' fa-angle-double-left',
				'fa-angle-double-right' => ' fa-angle-double-right',
				'fa-angle-double-up' => ' fa-angle-double-up',
				'fa-angle-down' => ' fa-angle-down',
				'fa-angle-left' => ' fa-angle-left',
				'fa-angle-right' => ' fa-angle-right',
				'fa-angle-up' => ' fa-angle-up',
				'fa-apple' => ' fa-apple',
				'fa-archive' => ' fa-archive',
				'fa-area-chart' => ' fa-area-chart',
				'fa-arrow-circle-down' => ' fa-arrow-circle-down',
				'fa-arrow-circle-left' => ' fa-arrow-circle-left',
				'fa-arrow-circle-o-down' => ' fa-arrow-circle-o-down',
				'fa-arrow-circle-o-left' => ' fa-arrow-circle-o-left',
				'fa-arrow-circle-o-right' => ' fa-arrow-circle-o-right',
				'fa-arrow-circle-o-up' => ' fa-arrow-circle-o-up',
				'fa-arrow-circle-right' => ' fa-arrow-circle-right',
				'fa-arrow-circle-up' => ' fa-arrow-circle-up',
				'fa-arrow-down' => ' fa-arrow-down',
				'fa-arrow-left' => ' fa-arrow-left',
				'fa-arrow-right' => ' fa-arrow-right',
				'fa-arrow-up' => ' fa-arrow-up',
				'fa-arrows' => ' fa-arrows',
				'fa-arrows-alt' => ' fa-arrows-alt',
				'fa-arrows-h' => ' fa-arrows-h',
				'fa-arrows-v' => ' fa-arrows-v',
				'fa-asterisk' => ' fa-asterisk',
				'fa-at' => ' fa-at',
				'fa-backward' => ' fa-backward',
				'fa-balance-scale' => ' fa-balance-scale',
				'fa-ban' => ' fa-ban',
				'fa-bar-chart' => ' fa-bar-chart',
				'fa-barcode' => ' fa-barcode',
				'fa-bars' => ' fa-bars',
				'fa-battery-empty' => ' fa-battery-empty',
				'fa-battery-full' => ' fa-battery-full',
				'fa-battery-half' => ' fa-battery-half',
				'fa-battery-quarter' => ' fa-battery-quarter',
				'fa-battery-three-quarters' => ' fa-battery-three-quarters',
				'fa-bed' => ' fa-bed',
				'fa-beer' => ' fa-beer',
				'fa-behance' => ' fa-behance',
				'fa-behance-square' => ' fa-behance-square',
				'fa-bell' => ' fa-bell',
				'fa-bell-o' => ' fa-bell-o',
				'fa-bell-slash' => ' fa-bell-slash',
				'fa-bell-slash-o' => ' fa-bell-slash-o',
				'fa-bicycle' => ' fa-bicycle',
				'fa-binoculars' => ' fa-binoculars',
				'fa-birthday-cake' => ' fa-birthday-cake',
				'fa-bitbucket' => ' fa-bitbucket',
				'fa-bitbucket-square' => ' fa-bitbucket-square',
				'fa-black-tie' => ' fa-black-tie',
				'fa-bold' => ' fa-bold',
				'fa-bolt' => ' fa-bolt',
				'fa-bomb' => ' fa-bomb',
				'fa-book' => ' fa-book',
				'fa-bookmark' => ' fa-bookmark',
				'fa-bookmark-o' => ' fa-bookmark-o',
				'fa-briefcase' => ' fa-briefcase',
				'fa-btc' => ' fa-btc',
				'fa-bug' => ' fa-bug',
				'fa-building' => ' fa-building',
				'fa-building-o' => ' fa-building-o',
				'fa-bullhorn' => ' fa-bullhorn',
				'fa-bullseye' => ' fa-bullseye',
				'fa-bus' => ' fa-bus',
				'fa-buysellads' => ' fa-buysellads',
				'fa-calculator' => ' fa-calculator',
				'fa-calendar' => ' fa-calendar',
				'fa-calendar-check-o' => ' fa-calendar-check-o',
				'fa-calendar-minus-o' => ' fa-calendar-minus-o',
				'fa-calendar-o' => ' fa-calendar-o',
				'fa-calendar-plus-o' => ' fa-calendar-plus-o',
				'fa-calendar-times-o' => ' fa-calendar-times-o',
				'fa-camera' => ' fa-camera',
				'fa-camera-retro' => ' fa-camera-retro',
				'fa-car' => ' fa-car',
				'fa-caret-down' => ' fa-caret-down',
				'fa-caret-left' => ' fa-caret-left',
				'fa-caret-right' => ' fa-caret-right',
				'fa-caret-square-o-down' => ' fa-caret-square-o-down',
				'fa-caret-square-o-left' => ' fa-caret-square-o-left',
				'fa-caret-square-o-right' => ' fa-caret-square-o-right',
				'fa-caret-square-o-up' => ' fa-caret-square-o-up',
				'fa-caret-up' => ' fa-caret-up',
				'fa-cart-arrow-down' => ' fa-cart-arrow-down',
				'fa-cart-plus' => ' fa-cart-plus',
				'fa-cc' => ' fa-cc',
				'fa-cc-amex' => ' fa-cc-amex',
				'fa-cc-diners-club' => ' fa-cc-diners-club',
				'fa-cc-discover' => ' fa-cc-discover',
				'fa-cc-jcb' => ' fa-cc-jcb',
				'fa-cc-mastercard' => ' fa-cc-mastercard',
				'fa-cc-paypal' => ' fa-cc-paypal',
				'fa-cc-stripe' => ' fa-cc-stripe',
				'fa-cc-visa' => ' fa-cc-visa',
				'fa-certificate' => ' fa-certificate',
				'fa-chain-broken' => ' fa-chain-broken',
				'fa-check' => ' fa-check',
				'fa-check-circle' => ' fa-check-circle',
				'fa-check-circle-o' => ' fa-check-circle-o',
				'fa-check-square' => ' fa-check-square',
				'fa-check-square-o' => ' fa-check-square-o',
				'fa-chevron-circle-down' => ' fa-chevron-circle-down',
				'fa-chevron-circle-left' => ' fa-chevron-circle-left',
				'fa-chevron-circle-right' => ' fa-chevron-circle-right',
				'fa-chevron-circle-up' => ' fa-chevron-circle-up',
				'fa-chevron-down' => ' fa-chevron-down',
				'fa-chevron-left' => ' fa-chevron-left',
				'fa-chevron-right' => ' fa-chevron-right',
				'fa-chevron-up' => ' fa-chevron-up',
				'fa-child' => ' fa-child',
				'fa-chrome' => ' fa-chrome',
				'fa-circle' => ' fa-circle',
				'fa-circle-o' => ' fa-circle-o',
				'fa-circle-o-notch' => ' fa-circle-o-notch',
				'fa-circle-thin' => ' fa-circle-thin',
				'fa-clipboard' => ' fa-clipboard',
				'fa-clock-o' => ' fa-clock-o',
				'fa-clone' => ' fa-clone',
				'fa-cloud' => ' fa-cloud',
				'fa-cloud-download' => ' fa-cloud-download',
				'fa-cloud-upload' => ' fa-cloud-upload',
				'fa-code' => ' fa-code',
				'fa-code-fork' => ' fa-code-fork',
				'fa-codepen' => ' fa-codepen',
				'fa-coffee' => ' fa-coffee',
				'fa-cog' => ' fa-cog',
				'fa-cogs' => ' fa-cogs',
				'fa-columns' => ' fa-columns',
				'fa-comment' => ' fa-comment',
				'fa-comment-o' => ' fa-comment-o',
				'fa-commenting' => ' fa-commenting',
				'fa-commenting-o' => ' fa-commenting-o',
				'fa-comments' => ' fa-comments',
				'fa-comments-o' => ' fa-comments-o',
				'fa-compass' => ' fa-compass',
				'fa-compress' => ' fa-compress',
				'fa-connectdevelop' => ' fa-connectdevelop',
				'fa-contao' => ' fa-contao',
				'fa-copyright' => ' fa-copyright',
				'fa-creative-commons' => ' fa-creative-commons',
				'fa-credit-card' => ' fa-credit-card',
				'fa-crop' => ' fa-crop',
				'fa-crosshairs' => ' fa-crosshairs',
				'fa-css3' => ' fa-css3',
				'fa-cube' => ' fa-cube',
				'fa-cubes' => ' fa-cubes',
				'fa-cutlery' => ' fa-cutlery',
				'fa-dashcube' => ' fa-dashcube',
				'fa-database' => ' fa-database',
				'fa-delicious' => ' fa-delicious',
				'fa-desktop' => ' fa-desktop',
				'fa-deviantart' => ' fa-deviantart',
				'fa-diamond' => ' fa-diamond',
				'fa-digg' => ' fa-digg',
				'fa-dot-circle-o' => ' fa-dot-circle-o',
				'fa-download' => ' fa-download',
				'fa-dribbble' => ' fa-dribbble',
				'fa-dropbox' => ' fa-dropbox',
				'fa-drupal' => ' fa-drupal',
				'fa-eject' => ' fa-eject',
				'fa-ellipsis-h' => ' fa-ellipsis-h',
				'fa-ellipsis-v' => ' fa-ellipsis-v',
				'fa-empire' => ' fa-empire',
				'fa-envelope' => ' fa-envelope',
				'fa-envelope-o' => ' fa-envelope-o',
				'fa-envelope-square' => ' fa-envelope-square',
				'fa-eraser' => ' fa-eraser',
				'fa-eur' => ' fa-eur',
				'fa-exchange' => ' fa-exchange',
				'fa-exclamation' => ' fa-exclamation',
				'fa-exclamation-circle' => ' fa-exclamation-circle',
				'fa-exclamation-triangle' => ' fa-exclamation-triangle',
				'fa-expand' => ' fa-expand',
				'fa-expeditedssl' => ' fa-expeditedssl',
				'fa-external-link' => ' fa-external-link',
				'fa-external-link-square' => ' fa-external-link-square',
				'fa-eye' => ' fa-eye',
				'fa-eye-slash' => ' fa-eye-slash',
				'fa-eyedropper' => ' fa-eyedropper',
				'fa-facebook' => ' fa-facebook',
				'fa-facebook-official' => ' fa-facebook-official',
				'fa-facebook-square' => ' fa-facebook-square',
				'fa-fast-backward' => ' fa-fast-backward',
				'fa-fast-forward' => ' fa-fast-forward',
				'fa-fax' => ' fa-fax',
				'fa-female' => ' fa-female',
				'fa-fighter-jet' => ' fa-fighter-jet',
				'fa-file' => ' fa-file',
				'fa-file-archive-o' => ' fa-file-archive-o',
				'fa-file-audio-o' => ' fa-file-audio-o',
				'fa-file-code-o' => ' fa-file-code-o',
				'fa-file-excel-o' => ' fa-file-excel-o',
				'fa-file-image-o' => ' fa-file-image-o',
				'fa-file-o' => ' fa-file-o',
				'fa-file-pdf-o' => ' fa-file-pdf-o',
				'fa-file-powerpoint-o' => ' fa-file-powerpoint-o',
				'fa-file-text' => ' fa-file-text',
				'fa-file-text-o' => ' fa-file-text-o',
				'fa-file-video-o' => ' fa-file-video-o',
				'fa-file-word-o' => ' fa-file-word-o',
				'fa-files-o' => ' fa-files-o',
				'fa-film' => ' fa-film',
				'fa-filter' => ' fa-filter',
				'fa-fire' => ' fa-fire',
				'fa-fire-extinguisher' => ' fa-fire-extinguisher',
				'fa-firefox' => ' fa-firefox',
				'fa-flag' => ' fa-flag',
				'fa-flag-checkered' => ' fa-flag-checkered',
				'fa-flag-o' => ' fa-flag-o',
				'fa-flask' => ' fa-flask',
				'fa-flickr' => ' fa-flickr',
				'fa-floppy-o' => ' fa-floppy-o',
				'fa-folder' => ' fa-folder',
				'fa-folder-o' => ' fa-folder-o',
				'fa-folder-open' => ' fa-folder-open',
				'fa-folder-open-o' => ' fa-folder-open-o',
				'fa-font' => ' fa-font',
				'fa-fonticons' => ' fa-fonticons',
				'fa-forumbee' => ' fa-forumbee',
				'fa-forward' => ' fa-forward',
				'fa-foursquare' => ' fa-foursquare',
				'fa-frown-o' => ' fa-frown-o',
				'fa-futbol-o' => ' fa-futbol-o',
				'fa-gamepad' => ' fa-gamepad',
				'fa-gavel' => ' fa-gavel',
				'fa-gbp' => ' fa-gbp',
				'fa-genderless' => ' fa-genderless',
				'fa-get-pocket' => ' fa-get-pocket',
				'fa-gg' => ' fa-gg',
				'fa-gg-circle' => ' fa-gg-circle',
				'fa-gift' => ' fa-gift',
				'fa-git' => ' fa-git',
				'fa-git-square' => ' fa-git-square',
				'fa-github' => ' fa-github',
				'fa-github-alt' => ' fa-github-alt',
				'fa-github-square' => ' fa-github-square',
				'fa-glass' => ' fa-glass',
				'fa-globe' => ' fa-globe',
				'fa-google' => ' fa-google',
				'fa-google-plus' => ' fa-google-plus',
				'fa-google-plus-square' => ' fa-google-plus-square',
				'fa-google-wallet' => ' fa-google-wallet',
				'fa-graduation-cap' => ' fa-graduation-cap',
				'fa-gratipay' => ' fa-gratipay',
				'fa-h-square' => ' fa-h-square',
				'fa-hacker-news' => ' fa-hacker-news',
				'fa-hand-lizard-o' => ' fa-hand-lizard-o',
				'fa-hand-o-down' => ' fa-hand-o-down',
				'fa-hand-o-left' => ' fa-hand-o-left',
				'fa-hand-o-right' => ' fa-hand-o-right',
				'fa-hand-o-up' => ' fa-hand-o-up',
				'fa-hand-paper-o' => ' fa-hand-paper-o',
				'fa-hand-peace-o' => ' fa-hand-peace-o',
				'fa-hand-pointer-o' => ' fa-hand-pointer-o',
				'fa-hand-rock-o' => ' fa-hand-rock-o',
				'fa-hand-scissors-o' => ' fa-hand-scissors-o',
				'fa-hand-spock-o' => ' fa-hand-spock-o',
				'fa-hdd-o' => ' fa-hdd-o',
				'fa-header' => ' fa-header',
				'fa-headphones' => ' fa-headphones',
				'fa-heart' => ' fa-heart',
				'fa-heart-o' => ' fa-heart-o',
				'fa-heartbeat' => ' fa-heartbeat',
				'fa-history' => ' fa-history',
				'fa-home' => ' fa-home',
				'fa-hospital-o' => ' fa-hospital-o',
				'fa-hourglass' => ' fa-hourglass',
				'fa-hourglass-end' => ' fa-hourglass-end',
				'fa-hourglass-half' => ' fa-hourglass-half',
				'fa-hourglass-o' => ' fa-hourglass-o',
				'fa-hourglass-start' => ' fa-hourglass-start',
				'fa-houzz' => ' fa-houzz',
				'fa-html5' => ' fa-html5',
				'fa-i-cursor' => ' fa-i-cursor',
				'fa-ils' => ' fa-ils',
				'fa-inbox' => ' fa-inbox',
				'fa-indent' => ' fa-indent',
				'fa-industry' => ' fa-industry',
				'fa-info' => ' fa-info',
				'fa-info-circle' => ' fa-info-circle',
				'fa-inr' => ' fa-inr',
				'fa-instagram' => ' fa-instagram',
				'fa-internet-explorer' => ' fa-internet-explorer',
				'fa-ioxhost' => ' fa-ioxhost',
				'fa-italic' => ' fa-italic',
				'fa-joomla' => ' fa-joomla',
				'fa-jpy' => ' fa-jpy',
				'fa-jsfiddle' => ' fa-jsfiddle',
				'fa-key' => ' fa-key',
				'fa-keyboard-o' => ' fa-keyboard-o',
				'fa-krw' => ' fa-krw',
				'fa-language' => ' fa-language',
				'fa-laptop' => ' fa-laptop',
				'fa-lastfm' => ' fa-lastfm',
				'fa-lastfm-square' => ' fa-lastfm-square',
				'fa-leaf' => ' fa-leaf',
				'fa-leanpub' => ' fa-leanpub',
				'fa-lemon-o' => ' fa-lemon-o',
				'fa-level-down' => ' fa-level-down',
				'fa-level-up' => ' fa-level-up',
				'fa-life-ring' => ' fa-life-ring',
				'fa-lightbulb-o' => ' fa-lightbulb-o',
				'fa-line-chart' => ' fa-line-chart',
				'fa-link' => ' fa-link',
				'fa-linkedin' => ' fa-linkedin',
				'fa-linkedin-square' => ' fa-linkedin-square',
				'fa-linux' => ' fa-linux',
				'fa-list' => ' fa-list',
				'fa-list-alt' => ' fa-list-alt',
				'fa-list-ol' => ' fa-list-ol',
				'fa-list-ul' => ' fa-list-ul',
				'fa-location-arrow' => ' fa-location-arrow',
				'fa-lock' => ' fa-lock',
				'fa-long-arrow-down' => ' fa-long-arrow-down',
				'fa-long-arrow-left' => ' fa-long-arrow-left',
				'fa-long-arrow-right' => ' fa-long-arrow-right',
				'fa-long-arrow-up' => ' fa-long-arrow-up',
				'fa-magic' => ' fa-magic',
				'fa-magnet' => ' fa-magnet',
				'fa-male' => ' fa-male',
				'fa-map' => ' fa-map',
				'fa-map-marker' => ' fa-map-marker',
				'fa-map-o' => ' fa-map-o',
				'fa-map-pin' => ' fa-map-pin',
				'fa-map-signs' => ' fa-map-signs',
				'fa-mars' => ' fa-mars',
				'fa-mars-double' => ' fa-mars-double',
				'fa-mars-stroke' => ' fa-mars-stroke',
				'fa-mars-stroke-h' => ' fa-mars-stroke-h',
				'fa-mars-stroke-v' => ' fa-mars-stroke-v',
				'fa-maxcdn' => ' fa-maxcdn',
				'fa-meanpath' => ' fa-meanpath',
				'fa-medium' => ' fa-medium',
				'fa-medkit' => ' fa-medkit',
				'fa-meh-o' => ' fa-meh-o',
				'fa-mercury' => ' fa-mercury',
				'fa-microphone' => ' fa-microphone',
				'fa-microphone-slash' => ' fa-microphone-slash',
				'fa-minus' => ' fa-minus',
				'fa-minus-circle' => ' fa-minus-circle',
				'fa-minus-square' => ' fa-minus-square',
				'fa-minus-square-o' => ' fa-minus-square-o',
				'fa-mobile' => ' fa-mobile',
				'fa-money' => ' fa-money',
				'fa-moon-o' => ' fa-moon-o',
				'fa-motorcycle' => ' fa-motorcycle',
				'fa-mouse-pointer' => ' fa-mouse-pointer',
				'fa-music' => ' fa-music',
				'fa-neuter' => ' fa-neuter',
				'fa-newspaper-o' => ' fa-newspaper-o',
				'fa-object-group' => ' fa-object-group',
				'fa-object-ungroup' => ' fa-object-ungroup',
				'fa-odnoklassniki' => ' fa-odnoklassniki',
				'fa-odnoklassniki-square' => ' fa-odnoklassniki-square',
				'fa-opencart' => ' fa-opencart',
				'fa-openid' => ' fa-openid',
				'fa-opera' => ' fa-opera',
				'fa-optin-monster' => ' fa-optin-monster',
				'fa-outdent' => ' fa-outdent',
				'fa-pagelines' => ' fa-pagelines',
				'fa-paint-brush' => ' fa-paint-brush',
				'fa-paper-plane' => ' fa-paper-plane',
				'fa-paper-plane-o' => ' fa-paper-plane-o',
				'fa-paperclip' => ' fa-paperclip',
				'fa-paragraph' => ' fa-paragraph',
				'fa-pause' => ' fa-pause',
				'fa-paw' => ' fa-paw',
				'fa-paypal' => ' fa-paypal',
				'fa-pencil' => ' fa-pencil',
				'fa-pencil-square' => ' fa-pencil-square',
				'fa-pencil-square-o' => ' fa-pencil-square-o',
				'fa-phone' => ' fa-phone',
				'fa-phone-square' => ' fa-phone-square',
				'fa-picture-o' => ' fa-picture-o',
				'fa-pie-chart' => ' fa-pie-chart',
				'fa-pied-piper' => ' fa-pied-piper',
				'fa-pied-piper-alt' => ' fa-pied-piper-alt',
				'fa-pinterest' => ' fa-pinterest',
				'fa-pinterest-p' => ' fa-pinterest-p',
				'fa-pinterest-square' => ' fa-pinterest-square',
				'fa-plane' => ' fa-plane',
				'fa-play' => ' fa-play',
				'fa-play-circle' => ' fa-play-circle',
				'fa-play-circle-o' => ' fa-play-circle-o',
				'fa-plug' => ' fa-plug',
				'fa-plus' => ' fa-plus',
				'fa-plus-circle' => ' fa-plus-circle',
				'fa-plus-square' => ' fa-plus-square',
				'fa-plus-square-o' => ' fa-plus-square-o',
				'fa-power-off' => ' fa-power-off',
				'fa-print' => ' fa-print',
				'fa-puzzle-piece' => ' fa-puzzle-piece',
				'fa-qq' => ' fa-qq',
				'fa-qrcode' => ' fa-qrcode',
				'fa-question' => ' fa-question',
				'fa-question-circle' => ' fa-question-circle',
				'fa-quote-left' => ' fa-quote-left',
				'fa-quote-right' => ' fa-quote-right',
				'fa-random' => ' fa-random',
				'fa-rebel' => ' fa-rebel',
				'fa-recycle' => ' fa-recycle',
				'fa-reddit' => ' fa-reddit',
				'fa-reddit-square' => ' fa-reddit-square',
				'fa-refresh' => ' fa-refresh',
				'fa-registered' => ' fa-registered',
				'fa-renren' => ' fa-renren',
				'fa-repeat' => ' fa-repeat',
				'fa-reply' => ' fa-reply',
				'fa-reply-all' => ' fa-reply-all',
				'fa-retweet' => ' fa-retweet',
				'fa-road' => ' fa-road',
				'fa-rocket' => ' fa-rocket',
				'fa-rss' => ' fa-rss',
				'fa-rss-square' => ' fa-rss-square',
				'fa-rub' => ' fa-rub',
				'fa-safari' => ' fa-safari',
				'fa-scissors' => ' fa-scissors',
				'fa-search' => ' fa-search',
				'fa-search-minus' => ' fa-search-minus',
				'fa-search-plus' => ' fa-search-plus',
				'fa-sellsy' => ' fa-sellsy',
				'fa-server' => ' fa-server',
				'fa-share' => ' fa-share',
				'fa-share-alt' => ' fa-share-alt',
				'fa-share-alt-square' => ' fa-share-alt-square',
				'fa-share-square' => ' fa-share-square',
				'fa-share-square-o' => ' fa-share-square-o',
				'fa-shield' => ' fa-shield',
				'fa-ship' => ' fa-ship',
				'fa-shirtsinbulk' => ' fa-shirtsinbulk',
				'fa-shopping-cart' => ' fa-shopping-cart',
				'fa-sign-in' => ' fa-sign-in',
				'fa-sign-out' => ' fa-sign-out',
				'fa-signal' => ' fa-signal',
				'fa-simplybuilt' => ' fa-simplybuilt',
				'fa-sitemap' => ' fa-sitemap',
				'fa-skyatlas' => ' fa-skyatlas',
				'fa-skype' => ' fa-skype',
				'fa-slack' => ' fa-slack',
				'fa-sliders' => ' fa-sliders',
				'fa-slideshare' => ' fa-slideshare',
				'fa-smile-o' => ' fa-smile-o',
				'fa-sort' => ' fa-sort',
				'fa-sort-alpha-asc' => ' fa-sort-alpha-asc',
				'fa-sort-alpha-desc' => ' fa-sort-alpha-desc',
				'fa-sort-amount-asc' => ' fa-sort-amount-asc',
				'fa-sort-amount-desc' => ' fa-sort-amount-desc',
				'fa-sort-asc' => ' fa-sort-asc',
				'fa-sort-desc' => ' fa-sort-desc',
				'fa-sort-numeric-asc' => ' fa-sort-numeric-asc',
				'fa-sort-numeric-desc' => ' fa-sort-numeric-desc',
				'fa-soundcloud' => ' fa-soundcloud',
				'fa-space-shuttle' => ' fa-space-shuttle',
				'fa-spinner' => ' fa-spinner',
				'fa-spoon' => ' fa-spoon',
				'fa-spotify' => ' fa-spotify',
				'fa-square' => ' fa-square',
				'fa-square-o' => ' fa-square-o',
				'fa-stack-exchange' => ' fa-stack-exchange',
				'fa-stack-overflow' => ' fa-stack-overflow',
				'fa-star' => ' fa-star',
				'fa-star-half' => ' fa-star-half',
				'fa-star-half-o' => ' fa-star-half-o',
				'fa-star-o' => ' fa-star-o',
				'fa-steam' => ' fa-steam',
				'fa-steam-square' => ' fa-steam-square',
				'fa-step-backward' => ' fa-step-backward',
				'fa-step-forward' => ' fa-step-forward',
				'fa-stethoscope' => ' fa-stethoscope',
				'fa-sticky-note' => ' fa-sticky-note',
				'fa-sticky-note-o' => ' fa-sticky-note-o',
				'fa-stop' => ' fa-stop',
				'fa-street-view' => ' fa-street-view',
				'fa-strikethrough' => ' fa-strikethrough',
				'fa-stumbleupon' => ' fa-stumbleupon',
				'fa-stumbleupon-circle' => ' fa-stumbleupon-circle',
				'fa-subscript' => ' fa-subscript',
				'fa-subway' => ' fa-subway',
				'fa-suitcase' => ' fa-suitcase',
				'fa-sun-o' => ' fa-sun-o',
				'fa-superscript' => ' fa-superscript',
				'fa-table' => ' fa-table',
				'fa-tablet' => ' fa-tablet',
				'fa-tachometer' => ' fa-tachometer',
				'fa-tag' => ' fa-tag',
				'fa-tags' => ' fa-tags',
				'fa-tasks' => ' fa-tasks',
				'fa-taxi' => ' fa-taxi',
				'fa-television' => ' fa-television',
				'fa-tencent-weibo' => ' fa-tencent-weibo',
				'fa-terminal' => ' fa-terminal',
				'fa-text-height' => ' fa-text-height',
				'fa-text-width' => ' fa-text-width',
				'fa-th' => ' fa-th',
				'fa-th-large' => ' fa-th-large',
				'fa-th-list' => ' fa-th-list',
				'fa-thumb-tack' => ' fa-thumb-tack',
				'fa-thumbs-down' => ' fa-thumbs-down',
				'fa-thumbs-o-down' => ' fa-thumbs-o-down',
				'fa-thumbs-o-up' => ' fa-thumbs-o-up',
				'fa-thumbs-up' => ' fa-thumbs-up',
				'fa-ticket' => ' fa-ticket',
				'fa-times' => ' fa-times',
				'fa-times-circle' => ' fa-times-circle',
				'fa-times-circle-o' => ' fa-times-circle-o',
				'fa-tint' => ' fa-tint',
				'fa-toggle-off' => ' fa-toggle-off',
				'fa-toggle-on' => ' fa-toggle-on',
				'fa-trademark' => ' fa-trademark',
				'fa-train' => ' fa-train',
				'fa-transgender' => ' fa-transgender',
				'fa-transgender-alt' => ' fa-transgender-alt',
				'fa-trash' => ' fa-trash',
				'fa-trash-o' => ' fa-trash-o',
				'fa-tree' => ' fa-tree',
				'fa-trello' => ' fa-trello',
				'fa-tripadvisor' => ' fa-tripadvisor',
				'fa-trophy' => ' fa-trophy',
				'fa-truck' => ' fa-truck',
				'fa-try' => ' fa-try',
				'fa-tty' => ' fa-tty',
				'fa-tumblr' => ' fa-tumblr',
				'fa-tumblr-square' => ' fa-tumblr-square',
				'fa-twitch' => ' fa-twitch',
				'fa-twitter' => ' fa-twitter',
				'fa-twitter-square' => ' fa-twitter-square',
				'fa-umbrella' => ' fa-umbrella',
				'fa-underline' => ' fa-underline',
				'fa-undo' => ' fa-undo',
				'fa-university' => ' fa-university',
				'fa-unlock' => ' fa-unlock',
				'fa-unlock-alt' => ' fa-unlock-alt',
				'fa-upload' => ' fa-upload',
				'fa-usd' => ' fa-usd',
				'fa-user' => ' fa-user',
				'fa-user-md' => ' fa-user-md',
				'fa-user-plus' => ' fa-user-plus',
				'fa-user-secret' => ' fa-user-secret',
				'fa-user-times' => ' fa-user-times',
				'fa-users' => ' fa-users',
				'fa-venus' => ' fa-venus',
				'fa-venus-double' => ' fa-venus-double',
				'fa-venus-mars' => ' fa-venus-mars',
				'fa-viacoin' => ' fa-viacoin',
				'fa-video-camera' => ' fa-video-camera',
				'fa-vimeo' => ' fa-vimeo',
				'fa-vimeo-square' => ' fa-vimeo-square',
				'fa-vine' => ' fa-vine',
				'fa-vk' => ' fa-vk',
				'fa-volume-down' => ' fa-volume-down',
				'fa-volume-off' => ' fa-volume-off',
				'fa-volume-up' => ' fa-volume-up',
				'fa-weibo' => ' fa-weibo',
				'fa-weixin' => ' fa-weixin',
				'fa-whatsapp' => ' fa-whatsapp',
				'fa-wheelchair' => ' fa-wheelchair',
				'fa-wifi' => ' fa-wifi',
				'fa-wikipedia-w' => ' fa-wikipedia-w',
				'fa-windows' => ' fa-windows',
				'fa-wordpress' => ' fa-wordpress',
				'fa-wrench' => ' fa-wrench',
				'fa-xing' => ' fa-xing',
				'fa-xing-square' => ' fa-xing-square',
				'fa-y-combinator' => ' fa-y-combinator',
				'fa-yahoo' => ' fa-yahoo',
				'fa-yelp' => ' fa-yelp',
				'fa-youtube' => ' fa-youtube',
				'fa-youtube-play' => ' fa-youtube-play',
				'fa-youtube-square' => ' fa-youtube-square',
			),
		),
				array (
					'key' => 'field_55d540539c518',
					'label' => 'Link',
					'name' => 'link-icon',
					'prefix' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'default_value' => '',
					'placeholder' => '',
					),
				),
			),
),
'location' => array (
	array (
		array (
			'param' => 'options_page',
			'operator' => '==',
			'value' => 'acf-options',
			),
		),
	),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_55d54a251c30f',
	'title' => 'Texto do Archive Meetup',
	'fields' => array (
		array (
			'key' => 'field_55d54a4803200',
			'label' => 'Título',
			'name' => 'titulo-archive-meetups',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
			),
		array (
			'key' => 'field_55d54a5703201',
			'label' => 'Descrição',
			'name' => 'descricao-archive-meetups',
			'prefix' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			),
		),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options',
				),
			),
		),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	));

register_field_group(array (
	'key' => 'group_55d54a74bcb52',
	'title' => 'Texto do Archive WordCamps',
	'fields' => array (
		array (
			'key' => 'field_55d54a74d3561',
			'label' => 'Título',
			'name' => 'titulo-archive-wordcamps',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
			),
		array (
			'key' => 'field_55d54a74d3610',
			'label' => 'Descrição',
			'name' => 'descricao-archive-wordcamps',
			'prefix' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			),
		),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options',
				),
			),
		),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	));

register_field_group(array (
	'key' => 'group_55d54382149e9',
	'title' => 'WordCamps',
	'fields' => array (
		array (
			'key' => 'field_55d5443f42885',
			'label' => 'Local',
			'name' => 'local-wordcamp',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
			),
		array (
			'key' => 'field_55d5444e42886',
			'label' => 'Link do site oficial',
			'name' => 'link-wordcamp',
			'prefix' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'default_value' => '',
			'placeholder' => '',
			),
),
'location' => array (
	array (
		array (
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'wordcamps',
			),
		),
	),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
));

}

if( function_exists('acf_add_local_field_group') ){
	acf_add_local_field_group(array (
		'key' => 'group_55db497279460',
		'title' => 'Configurações da Home',
		'fields' => array (
			array (
				'key' => 'field_55db497cf241b',
				'label' => 'Exibir destaque na home?',
				'name' => 'destaque-home',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'message' => '',
				'default_value' => 0,
				),
			array (
				'key' => 'field_55db4990f241c',
				'label' => 'Texto',
				'name' => 'texto-destaque-home',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_55db497cf241b',
							'operator' => '==',
							'value' => '1',
							),
						),
					),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				),
			array (
				'key' => 'field_55db49a7f241d',
				'label' => 'Exibir botão?',
				'name' => 'botao-destaque-home',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_55db497cf241b',
							'operator' => '==',
							'value' => '1',
							),
						),
					),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'message' => '',
				'default_value' => 0,
				),
			array (
				'key' => 'field_55db49bff241e',
				'label' => 'Texto do botão',
				'name' => 'texto-botao-home',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_55db49a7f241d',
							'operator' => '==',
							'value' => '1',
							),
						),
					),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
				),
			array (
				'key' => 'field_55db49d5f241f',
				'label' => 'Link do Botão',
				'name' => 'link-botao-home',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_55db49a7f241d',
							'operator' => '==',
							'value' => '1',
							),
						),
					),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'default_value' => '',
				'placeholder' => '',
				),
			array (
				'key' => 'field_55db4a71e06fd',
				'label' => 'Exibir próximo evento?',
				'name' => 'exibir-proximo-evento',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'message' => '',
				'default_value' => 0,
				),
			array (
				'key' => 'field_55db4ac7e06fe',
				'label' => 'Título da Seção',
				'name' => 'titulo-proximo-evento',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_55db4a71e06fd',
							'operator' => '==',
							'value' => '1',
							),
						),
					),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
				),
			array (
				'key' => 'field_55db4ae4e06ff',
				'label' => 'Escolher evento a ser exibido',
				'name' => 'objeto-proximo-evento',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_55db4a71e06fd',
							'operator' => '==',
							'value' => '1',
							),
						),
					),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'post_type' => array (
					0 => 'wordcamps',
					1 => 'meetups',
					),
				'taxonomy' => array (
					),
				'filters' => array (
					0 => 'search',
					1 => 'post_type',
					2 => 'taxonomy',
					),
				'elements' => array (
					0 => 'featured_image',
					),
				'min' => '',
				'max' => '',
				'return_format' => 'object',
				),
			array (
				'key' => 'field_55db4b5211912',
				'label' => 'Exibir evento anterior?',
				'name' => 'exibir-evento-passado',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'message' => '',
				'default_value' => 0,
				),
			array (
				'key' => 'field_55db4b5911913',
				'label' => 'Título da Seção',
				'name' => 'titulo-evento-passado',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_55db4b5211912',
							'operator' => '==',
							'value' => '1',
							),
						),
					),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
				),
			array (
				'key' => 'field_55db4b6511914',
				'label' => 'Escolher evento a ser exibido',
				'name' => 'objeto-evento-passado',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_55db4b5211912',
							'operator' => '==',
							'value' => '1',
							),
						),
					),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'post_type' => array (
					0 => 'wordcamps',
					1 => 'meetups',
					),
				'taxonomy' => array (
					),
				'filters' => array (
					0 => 'search',
					1 => 'post_type',
					2 => 'taxonomy',
					),
				'elements' => array (
					0 => 'featured_image',
					),
				'min' => '',
				'max' => '',
				'return_format' => 'object',
				),
			array (
				'key' => 'field_55db4f19fd29f',
				'label' => 'Exibir Slides?',
				'name' => 'exibir-slides',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'message' => '',
				'default_value' => 0,
				),
			array (
				'key' => 'field_55db4f2dfd2a0',
				'label' => 'Título',
				'name' => 'titulo-slides',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_55db4f19fd29f',
							'operator' => '==',
							'value' => '1',
							),
						),
					),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
				),
			array (
				'key' => 'field_55db4f42fd2a1',
				'label' => 'Selecionar Slides',
				'name' => 'slides-home',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_55db4f19fd29f',
							'operator' => '==',
							'value' => '1',
							),
						),
					),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'post_type' => array (
					0 => 'slides',
					),
				'taxonomy' => array (
					),
				'filters' => array (
					0 => 'search',
					1 => 'post_type',
					2 => 'taxonomy',
					),
				'elements' => array (
					0 => 'featured_image',
					),
				'min' => '',
				'max' => '',
				'return_format' => 'object',
				),
			array (
				'key' => 'field_55db4fb5fd2a2',
				'label' => 'Exibir Parceiros da Comunidade?',
				'name' => 'exibir-parceiros',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'message' => '',
				'default_value' => 0,
				),
			array (
				'key' => 'field_55db5008fd2a3',
				'label' => 'Cadastre aqui os parceiros',
				'name' => 'lista-parceiros',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_55db4fb5fd2a2',
							'operator' => '==',
							'value' => '1',
							),
						),
					),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'min' => '',
				'max' => '',
				'layout' => 'table',
				'button_label' => 'Adicionar Parceiro',
				'sub_fields' => array (
					array (
						'key' => 'field_55db502dfd2a4',
						'label' => 'Logo do parceiro',
						'name' => 'logo-parceiro',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
							),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						),
					array (
						'key' => 'field_55db505bfd2a5',
						'label' => 'Link do Parceiro',
						'name' => 'link-parceiro',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
							),
						'default_value' => '',
						'placeholder' => '',
						),
				),
),
),
'location' => array (
	array (
		array (
			'param' => 'options_page',
			'operator' => '==',
			'value' => 'acf-options',
			),
		),
	),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => 1,
'description' => '',
));
acf_add_local_field_group(array (
	'key' => 'group_55db4dfb0528c',
	'title' => 'CPT Slides',
	'fields' => array (
		array (
			'key' => 'field_55db4e005125a',
			'label' => 'Slides da palestras',
			'name' => 'link-slide',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
				),
			'default_value' => '',
			'placeholder' => '',
			),
		),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'slides',
				),
			),
		),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
	));
acf_add_local_field_group(array (
	'key' => 'group_55db4e5caf28c',
	'title' => 'Selecionar palestra',
	'fields' => array (
		array (
			'key' => 'field_55db4e76f01a1',
			'label' => 'Selecione os slides das palestras desejadas',
			'name' => 'slides-palestras',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
				),
			'post_type' => array (
				0 => 'slides',
				),
			'taxonomy' => array (
				),
			'filters' => array (
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
				),
			'elements' => array (
				0 => 'featured_image',
				),
			'min' => 1,
			'max' => '',
			'return_format' => 'object',
			),
		),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'wordcamps',
				),
			),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'meetups',
				),
			),
		),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
	));
}

if( function_exists('acf_add_local_field_group') ){

acf_add_local_field_group(array (
	'key' => 'group_55e07604ce277',
	'title' => 'Texto do Blog',
	'fields' => array (
		array (
			'key' => 'field_55e076351c52d',
			'label' => 'Exibir título e descrição no blog?',
			'name' => 'boolean-blog',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_55e0760c1c52c',
			'label' => 'Título do Blog',
			'name' => 'titulo-blog',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55e076351c52d',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55e0765d1c52e',
			'label' => 'Descrição do Blog',
			'name' => 'descriçao-blog',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55e076351c52d',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

}

define( 'ACF_LITE' , false );
