<?php

// Register Custom Post Type
function cpt_wordcamps() {

	$labels = array(
		'name'                => _x( 'WordCamps', 'wp-rio-locale' ),
		'singular_name'       => _x( 'WordCamp', 'wp-rio-locale' ),
		'menu_name'           => __( 'WordCamps', 'wp-rio-locale' ),
		'name_admin_bar'      => __( 'WordCamps', 'wp-rio-locale' ),
		'parent_item_colon'   => __( 'WordCamp Pai', 'wp-rio-locale' ),
		'all_items'           => __( 'Todos os WordCamp', 'wp-rio-locale' ),
		'add_new_item'        => __( 'Adicionar novo WordCamp', 'wp-rio-locale' ),
		'add_new'             => __( 'Adicionar novo', 'wp-rio-locale' ),
		'new_item'            => __( 'Adicionar novo', 'wp-rio-locale' ),
		'edit_item'           => __( 'Editar WordCamp', 'wp-rio-locale' ),
		'update_item'         => __( 'Atualizar WordCamp', 'wp-rio-locale' ),
		'view_item'           => __( 'Ver WordCamp', 'wp-rio-locale' ),
		'search_items'        => __( 'Buscar WordCamp', 'wp-rio-locale' ),
		'not_found'           => __( 'Não Encontrado', 'wp-rio-locale' ),
		'not_found_in_trash'  => __( 'Não Encontrado na Lixeira', 'wp-rio-locale' ),
	);
	$args = array(
		'label'               => __( 'Post Type', 'wp-rio-locale' ),
		'description'         => __( 'Postagens sobre os WordCamp', 'wp-rio-locale' ),
		'labels'              => $labels,
		'supports'            => array( 'title', 'editor', 'thumbnail' ),
		'taxonomies'          => array( ),
		'menu_icon'			  => 'dashicons-wordpress',
		'hierarchical'        => false,
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 5,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'can_export'          => true,
		'has_archive'         => true,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'capability_type'     => 'page',
	);
	register_post_type( 'wordcamps', $args );

}
add_action( 'init', 'cpt_wordcamps', 0 );

function cpt_meetups() {

	$labels = array(
		'name'                => _x( 'Meetups', 'wp-rio-locale' ),
		'singular_name'       => _x( 'Meetup', 'wp-rio-locale' ),
		'menu_name'           => __( 'Meetups', 'wp-rio-locale' ),
		'name_admin_bar'      => __( 'Meetups', 'wp-rio-locale' ),
		'parent_item_colon'   => __( 'Meetup Pai', 'wp-rio-locale' ),
		'all_items'           => __( 'Todos os Meetups', 'wp-rio-locale' ),
		'add_new_item'        => __( 'Adicionar novo Meetup', 'wp-rio-locale' ),
		'add_new'             => __( 'Adicionar novo', 'wp-rio-locale' ),
		'new_item'            => __( 'Adicionar novo', 'wp-rio-locale' ),
		'edit_item'           => __( 'Editar Meetup', 'wp-rio-locale' ),
		'update_item'         => __( 'Atualizar Meetup', 'wp-rio-locale' ),
		'view_item'           => __( 'Ver Meetup', 'wp-rio-locale' ),
		'search_items'        => __( 'Buscar Meetup', 'wp-rio-locale' ),
		'not_found'           => __( 'Não Encontrado', 'wp-rio-locale' ),
		'not_found_in_trash'  => __( 'Não Encontrado na Lixeira', 'wp-rio-locale' ),
	);
	$args = array(
		'label'               => __( 'Post Type', 'wp-rio-locale' ),
		'description'         => __( 'Postagens sobre os Meetups', 'wp-rio-locale' ),
		'labels'              => $labels,
		'supports'            => array( 'title', 'editor', 'thumbnail' ),
		'taxonomies'          => array( ),
		'menu_icon'			  => 'dashicons-wordpress-alt',
		'hierarchical'        => false,
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 5,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'can_export'          => true,
		'has_archive'         => true,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'capability_type'     => 'page',
	);
	register_post_type( 'meetups', $args );

}
add_action( 'init', 'cpt_meetups', 0 );

function cpt_slides() {

	$labels = array(
		'name'                => _x( 'Slides', 'wp-rio-locale' ),
		'singular_name'       => _x( 'Slide', 'wp-rio-locale' ),
		'menu_name'           => __( 'Slides', 'wp-rio-locale' ),
		'name_admin_bar'      => __( 'Slides', 'wp-rio-locale' ),
		'parent_item_colon'   => __( 'Slide Pai', 'wp-rio-locale' ),
		'all_items'           => __( 'Todos os slides', 'wp-rio-locale' ),
		'add_new_item'        => __( 'Adicionar novo slide', 'wp-rio-locale' ),
		'add_new'             => __( 'Adicionar novo', 'wp-rio-locale' ),
		'new_item'            => __( 'Adicionar novo', 'wp-rio-locale' ),
		'edit_item'           => __( 'Editar slide', 'wp-rio-locale' ),
		'update_item'         => __( 'Atualizar slide', 'wp-rio-locale' ),
		'view_item'           => __( 'Ver slide', 'wp-rio-locale' ),
		'search_items'        => __( 'Buscar slide', 'wp-rio-locale' ),
		'not_found'           => __( 'Não Encontrado', 'wp-rio-locale' ),
		'not_found_in_trash'  => __( 'Não Encontrado na Lixeira', 'wp-rio-locale' ),
	);
	$args = array(
		'label'               => __( 'Post Type', 'wp-rio-locale' ),
		'labels'              => $labels,
		'supports'            => array( 'title', 'editor', 'thumbnail' ),
		'taxonomies'          => array( ),
		'menu_icon'			  => 'dashicons-media-interactive',
		'hierarchical'        => false,
		'public'              => false,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'menu_position'       => 5,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'can_export'          => true,
		'has_archive'         => false,
		'exclude_from_search' => true,
		'publicly_queryable'  => true,
		'capability_type'     => 'page',
	);
	register_post_type( 'slides', $args );

}
add_action( 'init', 'cpt_slides', 0 );

// Register Custom Taxonomy
function taxonomy_cidades_wordcamp() {

	$labels = array(
		'name'                       => _x( 'Cidades', 'Taxonomy General Name', 'wp-rio-locale' ),
		'singular_name'              => _x( 'Cidade', 'Taxonomy Singular Name', 'wp-rio-locale' ),
		'menu_name'                  => __( 'Cidades', 'wp-rio-locale' ),
		'all_items'                  => __( 'Todas as Cidades', 'wp-rio-locale' ),
		'parent_item'                => __( 'Cidade Pai', 'wp-rio-locale' ),
		'parent_item_colon'          => __( 'Cidade Pai:', 'wp-rio-locale' ),
		'new_item_name'              => __( 'Nova Cidade', 'wp-rio-locale' ),
		'add_new_item'               => __( 'Adicionar Cidade', 'wp-rio-locale' ),
		'edit_item'                  => __( 'Editar Cidade', 'wp-rio-locale' ),
		'update_item'                => __( 'Atualizar Cidade', 'wp-rio-locale' ),
		'view_item'                  => __( 'Ver Cidade', 'wp-rio-locale' ),
		'separate_items_with_commas' => __( 'Separar cidades por vírgulas', 'wp-rio-locale' ),
		'add_or_remove_items'        => __( 'Adicionar ou Remover Cidades', 'wp-rio-locale' ),
		'choose_from_most_used'      => __( 'Escolher as mais usadas', 'wp-rio-locale' ),
		'popular_items'              => __( 'Cidades Populares', 'wp-rio-locale' ),
		'search_items'               => __( 'Buscar Cidades', 'wp-rio-locale' ),
		'not_found'                  => __( 'Não Encontrado', 'wp-rio-locale' ),
	);
	$args = array(
		'labels'                     => $labels,
		'hierarchical'               => true,
		'public'                     => true,
		'show_ui'                    => true,
		'show_admin_column'          => true,
		'show_in_nav_menus'          => true,
		'show_tagcloud'              => true,
	);
	register_taxonomy( 'cidades', array( 'meetups','wordcamps' ), $args );

}
add_action( 'init', 'taxonomy_cidades_wordcamp', 0 );

// Chamadas do ACF
if( function_exists('acf_add_options_page') ) {
	acf_add_options_page();
}

if( function_exists('register_field_group') ){
	register_field_group(array (
		'key' => 'group_55d545658bc53',
		'title' => 'Meetups',
		'fields' => array (
			array (
				'key' => 'field_55d545663c3f3',
				'label' => 'Local',
				'name' => 'local-meetup',
				'prefix' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_55d545663c7db',
				'label' => 'Link do site oficial',
				'name' => 'link-meetup',
				'prefix' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
			),
			array (
				'key' => 'field_55d545663c853',
				'label' => 'Palestras',
				'name' => 'palestras-meetup',
				'prefix' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'min' => '',
				'max' => '',
				'layout' => 'row',
				'button_label' => 'Adicionar Nova Palestra',
				'sub_fields' => array (
					array (
						'key' => 'field_55d54567d1208',
						'label' => 'Imagem de Capa',
						'name' => 'imagem-capa-meetup',
						'prefix' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'return_format' => 'id',
						'preview_size' => 'full',
						'library' => 'uploadedTo',
					),
					array (
						'key' => 'field_55d54567d1684',
						'label' => 'Link',
						'name' => 'link-palestra-meetup',
						'prefix' => '',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
					),
					array (
						'key' => 'field_55d54567d16ff',
						'label' => 'Título',
						'name' => 'titulo-meetup',
						'prefix' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_55d54567d17d0',
						'label' => 'Descrição',
						'name' => 'descricao-meetup',
						'prefix' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'meetups',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));

	register_field_group(array (
		'key' => 'group_55d546478739d',
		'title' => 'Quem Somos',
		'fields' => array (
			array (
				'key' => 'field_55d546fa6796e',
				'label' => 'Equipe',
				'name' => 'equipe',
				'prefix' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'min' => '',
				'max' => '',
				'layout' => 'row',
				'button_label' => 'Adicionar Linha',
				'sub_fields' => array (
					array (
						'key' => 'field_55d5470a6796f',
						'label' => 'Nome',
						'name' => 'nome-pessoa',
						'prefix' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_55d5473c67970',
						'label' => 'Foto Perfil',
						'name' => 'foto-perfil',
						'prefix' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'return_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_55d5478b67971',
						'label' => 'Descrição',
						'name' => 'descricao',
						'prefix' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
					),
					array (
						'key' => 'field_55d547f667972',
						'label' => 'Ícones Sociais',
						'name' => 'ícones-sociais',
						'prefix' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'min' => '',
						'max' => '',
						'layout' => 'row',
						'button_label' => 'Adicionar Linha',
						'sub_fields' => array (
							array (
								'key' => 'field_55d5481367973',
								'label' => 'Classe do ícone',
								'name' => 'classe-icone',
								'prefix' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'readonly' => 0,
								'disabled' => 0,
							),
							array (
								'key' => 'field_55d5484367974',
								'label' => 'Link da Rede',
								'name' => 'link-rede',
								'prefix' => '',
								'type' => 'url',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
							),
						),
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-quem-somos.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));

	register_field_group(array (
		'key' => 'group_55d53f4acc7a6',
		'title' => 'Rodapé',
		'fields' => array (
			array (
				'key' => 'field_55d541b66741a',
				'label' => 'Exibir ícones sociais',
				'name' => 'show-icons',
				'prefix' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_55d53f5172fd4',
				'label' => 'Ícones Sociais',
				'name' => 'social-icons',
				'prefix' => '',
				'type' => 'repeater',
				'instructions' => 'Adicionar a classe do glyphicon do Bootstrap - <a href="http://getbootstrap.com/components/#glyphicons" target="_blank">http://getbootstrap.com/components/#glyphicons</a>',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_55d541b66741a',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'min' => '',
				'max' => '',
				'layout' => 'row',
				'button_label' => 'Adicionar Novo',
				'sub_fields' => array (
					array (
						'key' => 'field_55d53fdb9c517',
						'label' => 'Classe do ícone',
						'name' => 'icon-class',
						'prefix' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_55d540539c518',
						'label' => 'Link',
						'name' => 'link-icon',
						'prefix' => '',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));

	register_field_group(array (
		'key' => 'group_55d54a251c30f',
		'title' => 'Texto do Archive Meetup',
		'fields' => array (
			array (
				'key' => 'field_55d54a4803200',
				'label' => 'Título',
				'name' => 'titulo-archive-meetups',
				'prefix' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_55d54a5703201',
				'label' => 'Descrição',
				'name' => 'descricao-archive-meetups',
				'prefix' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));

	register_field_group(array (
		'key' => 'group_55d54a74bcb52',
		'title' => 'Texto do Archive WordCamps',
		'fields' => array (
			array (
				'key' => 'field_55d54a74d3561',
				'label' => 'Título',
				'name' => 'titulo-archive-wordcamps',
				'prefix' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_55d54a74d3610',
				'label' => 'Descrição',
				'name' => 'descricao-archive-wordcamps',
				'prefix' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));

	register_field_group(array (
		'key' => 'group_55d54382149e9',
		'title' => 'WordCamps',
		'fields' => array (
			array (
				'key' => 'field_55d5443f42885',
				'label' => 'Local',
				'name' => 'local-wordcamp',
				'prefix' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_55d5444e42886',
				'label' => 'Link do site oficial',
				'name' => 'link-wordcamp',
				'prefix' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'default_value' => '',
				'placeholder' => '',
			),
			array (
				'key' => 'field_55d544a942887',
				'label' => 'Palestras',
				'name' => 'palestras-wordcamp',
				'prefix' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'min' => '',
				'max' => '',
				'layout' => 'row',
				'button_label' => 'Adicionar Nova Palestra',
				'sub_fields' => array (
					array (
						'key' => 'field_55d544c142888',
						'label' => 'Imagem de Capa',
						'name' => 'imagem-wordcamp',
						'prefix' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'return_format' => 'id',
						'preview_size' => 'full',
						'library' => 'uploadedTo',
					),
					array (
						'key' => 'field_55d544cf42889',
						'label' => 'Link',
						'name' => 'link-wordcamp',
						'prefix' => '',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
					),
					array (
						'key' => 'field_55d544da4288a',
						'label' => 'Título',
						'name' => 'titulo-wordcamp',
						'prefix' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_55d544e34288b',
						'label' => 'Descrição',
						'name' => 'descricao-wordcamp',
						'prefix' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'wordcamps',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));

	register_field_group(array (
		'key' => 'group_55db6a20ae0e0',
		'title' => 'Home',
		'fields' => array (
			array (
				'key' => 'field_55db6bf9dbf9a',
				'label' => 'Exibir área de parceiros',
				'name' => 'area-de-parceiros',
				'prefix' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_55db6bb5dbf96',
				'label' => 'Parceiros',
				'name' => 'parceiros',
				'prefix' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_55db6bf9dbf9a',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'min' => '',
				'max' => '',
				'layout' => 'row',
				'button_label' => 'Adicionar Parceiro',
				'sub_fields' => array (
					array (
						'key' => 'field_55db6bbfdbf97',
						'label' => 'Nome',
						'name' => 'nome-parceiro',
						'prefix' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_55db6bc7dbf98',
						'label' => 'Link',
						'name' => 'link-parceiro',
						'prefix' => '',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
					),
					array (
						'key' => 'field_55db6bd1dbf99',
						'label' => 'Logo',
						'name' => 'logo-parceiro',
						'prefix' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'column_width' => '',
						'return_format' => 'array',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
	));
}
define( 'ACF_LITE' , false );
